server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.h2.Driver
    password: password
    url: jdbc:h2:mem:testdb;DATABASE_TO_UPPER=false;DB_CLOSE_DELAY=-1
    username: sa
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true
